import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key= os.getenv("GROQ_API_KEY"))

SYSTEM_PROMPT = """You are a math reasoning assistant that solves grade school math problems.

For every problem, you must respond in EXACTLY this format and nothing else:

REASONING: <your step by step reasoning in plain english>
LEAN: theorem solution : <expression> = <answer> := by omega

Rules:
- The LEAN line must be a single valid Lean4 theorem
- Use only +, -, *, / operators and natural numbers
- The theorem must be provable by the omega tactic
- Do not add any imports or extra text
- Do not use variables, only concrete numbers

Example:
Problem: John has 5 apples. He buys 3 more. How many does he have?
REASONING: John starts with 5 apples and buys 3 more. Total = 5 + 3 = 8
LEAN: theorem solution : 5 + 3 = 8 := by omega"""

def generate_proof(problem: str) -> str:
    """
    Takes the gsm8k problem string.
    Returns the LEAN proof string generated by GROQ.
    """
    response = client.chat.completions.create(
        model = "llama-3.3-70b-versatile",
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},   
            {"role": "user", "content": f"Problem: {problem}"}],
        temperature = 0.1
    )

    raw = response.choices[0].message.content.strip()

    # Parse the response
    reasoning = " "
    lean_code = " "

    for line in raw.split("\n"):
        if line.startswith("REASONING:"):
            reasoning = line.replace("REASONING:", "").strip()
        elif line.startswith("LEAN:"):
            lean_code = line.replace("LEAN:", "").strip()

    return {
        "problem": problem,
        "reasoning": reasoning,
        "lean_code": lean_code,
        "raw": raw
    }

if __name__ == "__main__":
    problem = "Janet has 3 brothers and 5 sisters. How many siblings does she have in total?"
    result = generate_proof(problem)

    print("Problem:", result["problem"])
    print("Reasoning:", result["reasoning"])
    print("Lean:", result["lean_code"])
    print("---")
    print("Raw output:", result["raw"])