-- ============================================================
-- Verified Chain-of-Thought Solver — Lean4 Proof Examples
-- ============================================================
-- These are representative theorems generated by the LLM pipeline
-- and verified by Lean4's omega tactic.
-- Each theorem corresponds to a GSM8K-style math problem.
-- ============================================================


-- ── Basic arithmetic ─────────────────────────────────────────

-- Problem: John has 5 apples. He buys 3 more. How many does he have?
theorem ex1_addition : 5 + 3 = 8 := by omega

-- Problem: A bag has 20 marbles. 7 are removed. How many remain?
theorem ex2_subtraction : 20 - 7 = 13 := by omega

-- Problem: Each box holds 12 bottles. There are 8 boxes. How many bottles?
theorem ex3_multiplication : 12 * 8 = 96 := by omega


-- ── Multi-step reasoning ─────────────────────────────────────

-- Problem: Janet's ducks lay 16 eggs per day. She eats 3 for breakfast
-- and uses 4 for baking. She sells the rest at $2 each.
-- How much does she make daily?
-- Reasoning: 16 - 3 - 4 = 9 eggs remaining. 9 * 2 = $18
theorem ex4_janet_eggs : (16 - 3 - 4) * 2 = 18 := by omega

-- Problem: Janet has 3 brothers and 5 sisters.
-- How many siblings does she have in total?
-- Reasoning: 3 + 5 = 8
theorem ex5_siblings : 3 + 5 = 8 := by omega

-- Problem: A store has 48 apples. They sell 19 and receive 25 more.
-- How many apples are there now?
-- Reasoning: 48 - 19 + 25 = 54
theorem ex6_store_apples : 48 - 19 + 25 = 54 := by omega


-- ── Compound expressions ─────────────────────────────────────

-- Problem: Toulouse has twice as many sheep as Charleston.
-- Charleston has 4 times as many as Seattle.
-- Seattle has 20 sheep. How many in total?
-- Reasoning: Seattle=20, Charleston=80, Toulouse=160. Total=260
theorem ex7_sheep : 20 + 4 * 20 + 2 * (4 * 20) = 260 := by omega

-- Problem: James runs 3 sprints, 3 times a week, 60 meters each.
-- How many meters per week?
-- Reasoning: 3 * 3 * 60 = 540
theorem ex8_james_runs : 3 * 3 * 60 = 540 := by omega

-- Problem: Kylar buys 16 glasses. One glass costs $5,
-- every second glass costs 60% = $3. How much total?
-- Reasoning: 8 full price + 8 half price = 8*5 + 8*3 = 64
theorem ex9_kylar_glasses : 8 * 5 + 8 * 3 = 64 := by omega

-- Problem: Anakin caught 10 starfish, 6 sea horses, 3 clownfish.
-- Locsin caught 5 fewer starfish, 3 fewer sea horses, 2 more clownfish.
-- How many total?
-- Reasoning: (10+6+3) + (10-5) + (6-3) + (3+2) = 19 + 5 + 3 + 5 = 32
theorem ex10_beach_catch : (10 + 6 + 3) + (10 - 5) + (6 - 3) + (3 + 2) = 32 := by omega


-- ── Repair loop examples ─────────────────────────────────────
-- These theorems were initially generated incorrectly and
-- fixed by the repair loop after Lean returned an error.

-- Problem: Josh buys a house for $80,000, puts in $50,000 repairs.
-- Value increased by 150%. Profit?
-- First attempt (WRONG): theorem solution : 150000 - 130000 = 70000  ← rejected
-- Repaired (CORRECT):
-- Reasoning: Value = 80000 * 2.5 = 200000. Cost = 80000+50000 = 130000. Profit = 70000
theorem ex11_josh_house : 200000 - 130000 = 70000 := by omega

-- Problem: Wendi feeds 20 chickens 3 cups each = 60 cups total.
-- Morning: 15 cups. Afternoon: 25 cups. Final meal = ?
-- Reasoning: 60 - 15 - 25 = 20
theorem ex12_wendi_chickens : 3 * 20 - 15 - 25 = 20 := by omega


-- ── Verifier behavior demonstration ──────────────────────────
-- This section shows what happens when omega succeeds vs fails.

-- PASSES: linear arithmetic, integers only
theorem verify_pass_1 : 2 + 3 = 5 := by omega
theorem verify_pass_2 : 100 - 37 = 63 := by omega
theorem verify_pass_3 : 7 * 8 = 56 := by omega
theorem verify_pass_4 : ∀ n : Nat, n + 0 = n := by intro n; omega

-- NOTE: The following would FAIL with omega and are NOT included:
-- theorem fail_1 : 60 / 4 * 5 = 75 := by omega   -- division not supported
-- theorem fail_2 : 20 * 3 / 2 = 30 := by omega   -- fractional intermediate
-- theorem fail_3 : 2 ^ 10 = 1024 := by omega      -- exponentiation not supported
